export const inviteCopy = {
  section: "Pessoas",
  generateButton: "Gerar código de acesso",
  generateHint: "Vale 5 minutos e serve para uma pessoa.",
  generateWillInvalidate: "Gerar novo código vai invalidar o atual.",
  expiresIn: (countdown: string) => `expira em ${countdown}`,
  copy: "Copiar código",
  copied: "Copiado",
  cancel: "Cancelar código",
  cancelConfirm: "Cancelar este código?",
  cancelConfirmAction: "Cancelar código",
  cancelKeep: "Manter",
  activeWithoutValue: (countdown: string) =>
    `Existe um código ativo, expira em ${countdown}.`,
  expired: "O código expirou.",
  redeemed: (name: string) => `${name} entrou.`,
  atCapacity: "Limite de 10 pessoas atingido.",
  generateNew: "Gerar novo código",
  joinTitle: "Entrar com código",
  joinHint: "Peça o código para quem administra o workspace.",
  joinField: "Código de acesso",
  joinButton: "Entrar",
  redeemError: "Código de acesso inválido.",
  tooManyAttempts: "Muitas tentativas. Tente novamente em alguns minutos.",
  alreadyMember: (name: string) => `Você já faz parte de ${name}.`,
  removeConfirm: (name: string) =>
    `Remover ${name}? Ele perde acesso a este workspace.`,
  removed: (name: string) => `${name} foi removido.`,
  roleOwner: "Dono",
  roleAdmin: "Administrador",
  roleMember: "Membro",
  personalWorkspace: "Espaço pessoal",
  memberCount: (n: number) => `${n} de 10 pessoas`,
  remove: "Remover",
  removeAction: "Remover",
  keep: "Cancelar",
} as const;
